version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export PATH=./node_modules/.bin:$PATH
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo Initializing AWS variables...
      - |
        export CREDS=$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)
        export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .AccessKeyId)
        export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .SecretAccessKey)
        export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .Token)
        export AWS_DEFAULT_REGION=us-east-2
        export AWS_ACCOUNT_NUMBER=$(aws sts get-caller-identity --query Account --output text)
  build:
    commands:
      - echo Build started on `date`
      - |
        if [[ "$CODEBUILD_INITIATOR" =~ ^codepipeline* ]]; then
          echo Logging in to Amazon ECR...
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          echo "START -- Build and Publish Docker Image: amazon-linux-v2-node-v18-libre-office-v7-6-2-x86-64"
          docker build -t amazon-linux-v2-node-v18-libre-office-v7-6-2-x86-64:latest ./amazon-linux-v2-node-v18-libre-office-v7-6-2-x86-64
          docker tag amazon-linux-v2-node-v18-libre-office-v7-6-2-x86-64:latest $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/amazon-linux-v2-node-v18-libre-office-v7-6-2-x86-64:latest
          aws ecr describe-repositories --repository-names amazon-linux-v2-node-v18-libre-office-v7-6-2-x86-64 || aws ecr create-repository --repository-name amazon-linux-v2-node-v18-libre-office-v7-6-2-x86-64
          docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/amazon-linux-v2-node-v18-libre-office-v7-6-2-x86-64:latest
          echo "END -- Build and Publish Docker Image: amazon-linux-v2-node-v18-libre-office-v7-6-2-x86-64"
        else 
          echo "Not running in CodePipeline, skipping build and publish"
        fi

  post_build:
    commands:
